/** Sample data for the demo account. Always labelled as sample data in the UI. */

export const DEMO_EMAIL = "demo@hunarhisaab.pk";
export const DEMO_PASSWORD = "hunarhisaab-demo-2025";

export const SAMPLE_WHATSAPP_MESSAGE =
  "Assalam o alaikum baji, 3 green embroidered suits chahiye 23rd tak. 4200 each theek hain? delivery DHA Lahore. advance easypaisa kar doon?";

export const SAMPLE_MESSAGES = [
  SAMPLE_WHATSAPP_MESSAGE,
  "Baji AoA, beti ki birthday hai 18 tareekh ko. 2 kg chocolate cake chahiye, gulab ka design. Gulberg Lahore deliver ho jayega? Cash de dungi. 5500 ka ban jayega?",
  "Salam, mehndi function 26 ko hai. Dulhan ke full hands aur feet, plus 4 guests ke simple designs. Bahria Town Rawalpindi. JazzCash pe advance bhej doon?",
];

export const DEMO_ORDERS = [
  {
    customer_name: "Ayesha Tariq",
    item: "Embroidered suit (green, 3-piece)",
    quantity: 3,
    unit_price: 4200,
    material_cost: 2200,
    labor_hours: 6,
    hourly_labor_value: 200,
    packaging_cost: 120,
    delivery_cost: 350,
    other_cost: 0,
    desired_profit_percent: 25,
    deadline_text: "23rd",
    delivery_area: "DHA, Lahore",
    payment_method: "Easypaisa",
    notes: "Advance on Easypaisa. Sample data.",
    status: "confirmed" as const,
    daysAgo: 12,
    confirmed: true,
  },
  {
    customer_name: "Hina Malik",
    item: "Chocolate truffle cake (2 kg)",
    quantity: 1,
    unit_price: 5500,
    material_cost: 2400,
    labor_hours: 4,
    hourly_labor_value: 250,
    packaging_cost: 250,
    delivery_cost: 300,
    other_cost: 100,
    desired_profit_percent: 30,
    deadline_text: "18 tareekh",
    delivery_area: "Gulberg, Lahore",
    payment_method: "Cash",
    notes: "Rose design on top. Sample data.",
    status: "confirmed" as const,
    daysAgo: 6,
    confirmed: true,
  },
  {
    customer_name: "Sadia Rehman",
    item: "Bridal mehndi + 4 guest designs",
    quantity: 1,
    unit_price: 12000,
    material_cost: 1500,
    labor_hours: 7,
    hourly_labor_value: 800,
    packaging_cost: 0,
    delivery_cost: 500,
    other_cost: 0,
    desired_profit_percent: 35,
    deadline_text: "26th",
    delivery_area: "Bahria Town, Rawalpindi",
    payment_method: "JazzCash",
    notes: "Function at home. Sample data.",
    status: "pending" as const,
    daysAgo: 2,
    confirmed: false,
  },
  {
    customer_name: "Nimra Shahid",
    item: "Frozen samosas (dozen packs)",
    quantity: 8,
    unit_price: 550,
    material_cost: 260,
    labor_hours: 0.5,
    hourly_labor_value: 200,
    packaging_cost: 40,
    delivery_cost: 200,
    other_cost: 0,
    desired_profit_percent: 20,
    deadline_text: "Friday",
    delivery_area: "Johar Town, Lahore",
    payment_method: "Bank transfer",
    notes: "Repeat customer. Sample data.",
    status: "confirmed" as const,
    daysAgo: 19,
    confirmed: true,
  },
  {
    customer_name: "Rabia Anwar",
    item: "Crochet baby set (cap + booties)",
    quantity: 4,
    unit_price: 1800,
    material_cost: 700,
    labor_hours: 3,
    hourly_labor_value: 200,
    packaging_cost: 60,
    delivery_cost: 250,
    other_cost: 0,
    desired_profit_percent: 25,
    deadline_text: "Next week",
    delivery_area: "Clifton, Karachi",
    payment_method: "Easypaisa",
    notes: "Sample data.",
    status: "draft" as const,
    daysAgo: 1,
    confirmed: false,
  },
];
